---
title: NÉSTOR MONTAÑO
---



Ingeniero en estadística informática, maestrante en estadística con mención en gestión de la calidad productividad (ambos programas desarrollados en ESPOL) y miembro del directorio de la Sociedad ecuatoriana de estadística SEE

Cuenta con experiencia profesional de más de 10 años en el sector privado, se desempeñó como ingeniero de procesos especialista en el área matemático-estadística del grupo Crecos (actualmente Crecoscorp S.A.), realizó análisis de mercado en la empresa Productos Metalúrgicos S.A. a más de coordinar consultorías (área estadística y gis) para instituciones del sector privado y público como Syngenta, Muy Ilustre municipalidad de Guayaquil, Ministerio de agricultura, mientras laboraba para una reconocida consultora ambiental. En el presente, trabaja como jefe de planificación de demanda e inteligencia de negocios en una importante y reconocida empresa comercial del sector ferretero, como consultor privado a través de la empresa MASSAP S.A. además es capacitador de la SEE e instituciones privadas en el lenguaje de programación R y estadística en general.

Colabora constantemente con la academia a través de participaciones en eventos o dictado de diversos cursos y conferencias para estudiantes de pregrado o profesionales, sus áreas de interés son: muestreo, estadística multivariante, forecasting, algoritmos de clasificación, optimización, inteligencia de negocios y desarrollo de aplicaciones estadísticas.